---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: podcliqueset-validating-webhook
  namespace: {{ .Release.Namespace }}
  {{- if .Values.webhooks.podCliqueSetValidationWebhook.annotations }}
  annotations:
    {{- toYaml .Values.webhooks.podCliqueSetValidationWebhook.annotations | nindent 4 }}
  {{- end }}
  labels:
{{- include "operator.pcs.validating.webhook.labels" . | nindent 4 }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      {{- if .Values.webhooks.podCliqueSetValidationWebhook.caBundle }}
      caBundle: {{ .Values.webhooks.podCliqueSetValidationWebhook.caBundle }}
      {{- end }}
      service:
        name: {{ required ".Values.service.name is required" .Values.service.name }}
        namespace: {{ .Release.Namespace }}
        path: /webhooks/validate-podcliqueset
        port: {{ required ".Values.config.server.webhooks.port" .Values.config.server.webhooks.port }}
    failurePolicy: Fail
    matchPolicy: Exact
    name: pcs.validating.webhooks.grove.io
    namespaceSelector: { }
    rules:
      - apiGroups:
          - "grove.io"
        apiVersions:
          - "v1alpha1"
        operations:
          - CREATE
          - UPDATE
        resources:
          - podcliquesets
        scope: "Namespaced"
    sideEffects: None
    timeoutSeconds: 10
