---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: podcliqueset-validating-webhook
  labels:
{{- include "operator.pcs.validating.webhook.labels" . | nindent 4 }}
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      {{- if .Values.config.server.webhooks.secretName }}
      # CA Bundle from secret
      {{- $secret := lookup "v1" "Secret" .Release.Namespace .Values.config.server.webhooks.secretName }}
      {{- if $secret }}
      caBundle: {{ index $secret.data "ca.crt" }}
      {{- end }}
      {{- end }}
      service:
        name: {{ required ".Values.service.name is required" .Values.service.name }}
        namespace: {{ .Release.Namespace }}
        path: /webhooks/validate-podcliqueset
        port: {{ required ".Values.config.server.webhooks.port" .Values.config.server.webhooks.port }}
    failurePolicy: Fail
    matchPolicy: Exact
    name: pcs.validating.webhooks.grove.io
    namespaceSelector: { }
    rules:
      - apiGroups:
          - "grove.io"
        apiVersions:
          - "v1alpha1"
        operations:
          - CREATE
          - UPDATE
        resources:
          - podcliquesets
        scope: "Namespaced"
    sideEffects: None
    timeoutSeconds: 10
